name: Run AWS Spec tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1" # Every Monday

permissions:
  contents: write
  id-token: write
  packages: write

jobs:        
  run-aws-test-kitchen:
    uses: observeinc/aws-test-kitchen/.github/workflows/ci.yml@main
    with:
      test_type: terraform
      code_sha: ${{ github.sha }}
    secrets:
      OBSERVE_CUSTOMER: ${{ secrets.OBSERVE_CUSTOMER }}
      OBSERVE_TOKEN: ${{ secrets.OBSERVE_TOKEN }}
      OBSERVE_DOMAIN: ${{ secrets.OBSERVE_DOMAIN }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
